services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ncs_backend
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./backend.env
    depends_on:
      - mongodb
    command: yarn start
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_REACT_APP_API_URL: http://localhost:3000
    container_name: ncs_frontend
    restart: always
    ports:
      - 8080:80

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ncs
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
